/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ExpansiveGraphPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// node_modules/monkey-around/dist/index.mjs
function around(obj, factories) {
  const removers = Object.keys(factories).map((key) => around1(obj, key, factories[key]));
  return removers.length === 1 ? removers[0] : function() {
    removers.forEach((r) => r());
  };
}
function around1(obj, method, createWrapper) {
  const inherited = obj[method], hadOwn = obj.hasOwnProperty(method), original = hadOwn ? inherited : function() {
    return Object.getPrototypeOf(obj)[method].apply(this, arguments);
  };
  let current = createWrapper(original);
  if (inherited)
    Object.setPrototypeOf(current, inherited);
  Object.setPrototypeOf(wrapper, current);
  obj[method] = wrapper;
  return remove;
  function wrapper(...args) {
    if (current === original && obj[method] === wrapper)
      remove();
    return current.apply(this, args);
  }
  function remove() {
    if (obj[method] === wrapper) {
      if (hadOwn)
        obj[method] = original;
      else
        delete obj[method];
    }
    if (current === original)
      return;
    current = original;
    Object.setPrototypeOf(wrapper, inherited || Function);
  }
}

// main.ts
var ExpansiveGraphPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.rightClickPatched = /* @__PURE__ */ new WeakSet();
    this.queueRenderPatched = /* @__PURE__ */ new WeakSet();
    this.lastMenuPosition = null;
    this.overridesByLeaf = /* @__PURE__ */ new WeakMap();
    this.overlayByLeaf = /* @__PURE__ */ new WeakMap();
    this.offsetsByLeaf = /* @__PURE__ */ new WeakMap();
    this.branchCounterByLeaf = /* @__PURE__ */ new WeakMap();
    this.ROOT_RADIUS = 130;
    this.CHILD_RADIUS = 110;
    this.MAX_RADIUS_MULT = 3.5;
    this.ROW_GAP = 48;
    this.RELAX_ITERS = 30;
    this.NODE_PADDING = 14;
    this.PALETTE = [
      7252222,
      16752451,
      5034295,
      14702333,
      16697943,
      53971,
      16739179,
      5546239
    ];
  }
  async onload() {
    this.registerEvent(
      this.app.workspace.on("layout-change", () => this.patchAllLocalGraphs())
    );
    new import_obsidian.Notice("Expansive Graph loaded");
    this.patchAllLocalGraphs();
  }
  // ─── PATCHING ────────────────────────────────────────────────────────────
  patchAllLocalGraphs() {
    for (const leaf of this.app.workspace.getLeavesOfType("localgraph")) {
      const view = leaf == null ? void 0 : leaf.view;
      if (!view)
        continue;
      this.patchRightClick(leaf, view);
      const renderer = view == null ? void 0 : view.renderer;
      if (renderer && typeof renderer.queueRender === "function" && !this.queueRenderPatched.has(renderer)) {
        this.patchQueueRender(leaf, renderer);
      }
    }
  }
  patchRightClick(leaf, view) {
    const targets = [view, view == null ? void 0 : view.engine, view == null ? void 0 : view.renderer].filter(Boolean);
    for (const target of targets) {
      if (!target || this.rightClickPatched.has(target) || typeof target.onNodeRightClick !== "function")
        continue;
      this.rightClickPatched.add(target);
      this.register(
        around(target, {
          onNodeRightClick: (orig) => {
            const plugin = this;
            return function(...args) {
              const event = plugin.findMouseEvent(args);
              const nodePath = plugin.extractPathFromArgs(args);
              const result = orig == null ? void 0 : orig.apply(this, args);
              if (!event || !nodePath)
                return result;
              plugin.lastMenuPosition = { x: event.clientX, y: event.clientY };
              const menu = new import_obsidian.Menu();
              plugin.buildBranchMenu(menu, leaf, view, nodePath, true);
              setTimeout(() => {
                var _a;
                const pos = (_a = plugin.lastMenuPosition) != null ? _a : { x: window.innerWidth / 2, y: window.innerHeight / 2 };
                menu.showAtPosition(pos);
              }, 0);
              return result;
            };
          }
        })
      );
    }
  }
  patchQueueRender(leaf, renderer) {
    this.queueRenderPatched.add(renderer);
    this.register(
      around(renderer, {
        queueRender: (orig) => {
          const plugin = this;
          return function(...args) {
            const result = orig == null ? void 0 : orig.apply(this, args);
            try {
              plugin.drawOverlay(leaf, renderer);
            } catch (e) {
              console.warn("[ExpGraph] drawOverlay error", e);
            }
            return result;
          };
        }
      })
    );
  }
  // ─── MENU ─────────────────────────────────────────────────────────────────
  buildBranchMenu(menu, leaf, view, nodePath, isRootMenu = false) {
    var _a;
    const overrides = this.getOverrides(leaf);
    const branch = overrides.get(nodePath);
    const depth = (_a = branch == null ? void 0 : branch.depth) != null ? _a : 0;
    const label = this.basename(nodePath).replace(/\.md$/i, "");
    menu.addItem(
      (item) => item.setTitle(`Expand ${isRootMenu ? "here" : label} (+1) [depth=${depth}]`).setIcon("plus-circle").onClick(() => {
        this.ensureBranch(leaf, nodePath, 1);
        this.safeRefresh(view);
      })
    );
    menu.addItem(
      (item) => item.setTitle(isRootMenu ? "Reduce here (-1)" : `Reduce ${label} (-1)`).setIcon("minus-circle").setDisabled(depth <= 0).onClick(() => {
        this.reduceBranch(leaf, nodePath);
        this.safeRefresh(view);
      })
    );
    menu.addItem(
      (item) => item.setTitle(isRootMenu ? "Reset this branch" : `Reset ${label}`).setIcon("rotate-ccw").setDisabled(depth <= 0).onClick(() => {
        this.getOverrides(leaf).delete(nodePath);
        this.safeRefresh(view);
      })
    );
    const expandedChildren = this.getExpandedOverlayChildrenForBranch(leaf, view, nodePath);
    if (expandedChildren.length) {
      menu.addSeparator();
      menu.addItem(
        (item) => item.setTitle(`Expanded children (${expandedChildren.length})`).setIcon("list-tree").onClick(() => {
          var _a2, _b;
          const childListMenu = new import_obsidian.Menu();
          for (const childPath of expandedChildren) {
            const childDepth = (_b = (_a2 = overrides.get(childPath)) == null ? void 0 : _a2.depth) != null ? _b : 0;
            const childLabel = this.basename(childPath).replace(/\.md$/i, "");
            childListMenu.addItem(
              (childItem) => childItem.setTitle(`${childLabel}${childDepth > 0 ? ` [${childDepth}]` : ""}`).setIcon("dot-network").onClick(() => {
                const childMenu = new import_obsidian.Menu();
                this.buildBranchMenu(childMenu, leaf, view, childPath, false);
                setTimeout(() => {
                  const pos = this.bumpMenuPosition();
                  childMenu.showAtPosition(pos);
                }, 0);
              })
            );
          }
          setTimeout(() => {
            const pos = this.bumpMenuPosition();
            childListMenu.showAtPosition(pos);
          }, 0);
        })
      );
    }
    if (isRootMenu) {
      menu.addSeparator();
      menu.addItem(
        (item) => item.setTitle("Reset ALL expansions").setIcon("rotate-ccw").onClick(() => {
          this.overridesByLeaf.set(leaf, /* @__PURE__ */ new Map());
          this.offsetsByLeaf.set(leaf, /* @__PURE__ */ new Map());
          this.branchCounterByLeaf.set(leaf, 0);
          this.clearOverlay(leaf);
          this.safeRefresh(view);
        })
      );
    }
  }
  getExpandedOverlayChildrenForBranch(leaf, view, rootPath) {
    var _a, _b;
    const branchDepth = (_b = (_a = this.getOverrides(leaf).get(rootPath)) == null ? void 0 : _a.depth) != null ? _b : 0;
    if (branchDepth <= 0)
      return [];
    const renderer = view == null ? void 0 : view.renderer;
    if (!renderer)
      return [];
    const nativeNodes = this.collectRenderedNodes(renderer);
    const nativePaths = /* @__PURE__ */ new Set();
    for (const node of nativeNodes) {
      const path = this.extractNodeId(node);
      if (path)
        nativePaths.add(path);
    }
    const offsets = this.getOffsets(leaf);
    const directNeighbors = this.getNeighbors(rootPath);
    return directNeighbors.filter((path) => {
      if (path === rootPath)
        return false;
      if (nativePaths.has(path))
        return false;
      return offsets.has(path) || this.getOverrides(leaf).has(path);
    }).sort((a, b) => this.basename(a).localeCompare(this.basename(b)));
  }
  bumpMenuPosition() {
    var _a;
    const base = (_a = this.lastMenuPosition) != null ? _a : { x: window.innerWidth / 2, y: window.innerHeight / 2 };
    const next = {
      x: Math.min(base.x + 28, window.innerWidth - 260),
      y: Math.min(base.y + 18, window.innerHeight - 80)
    };
    this.lastMenuPosition = next;
    return next;
  }
  // ─── BRANCH STATE ─────────────────────────────────────────────────────────
  getOverrides(leaf) {
    let m = this.overridesByLeaf.get(leaf);
    if (!m) {
      m = /* @__PURE__ */ new Map();
      this.overridesByLeaf.set(leaf, m);
    }
    return m;
  }
  getOffsets(leaf) {
    let m = this.offsetsByLeaf.get(leaf);
    if (!m) {
      m = /* @__PURE__ */ new Map();
      this.offsetsByLeaf.set(leaf, m);
    }
    return m;
  }
  ensureBranch(leaf, path, delta = 1) {
    var _a;
    const overrides = this.getOverrides(leaf);
    const existing = overrides.get(path);
    if (existing) {
      const next = { ...existing, depth: existing.depth + delta };
      overrides.set(path, next);
      return next;
    }
    const counter = (_a = this.branchCounterByLeaf.get(leaf)) != null ? _a : 0;
    this.branchCounterByLeaf.set(leaf, counter + 1);
    const created = {
      depth: Math.max(1, delta),
      color: this.PALETTE[counter % this.PALETTE.length],
      order: counter
    };
    overrides.set(path, created);
    return created;
  }
  reduceBranch(leaf, path) {
    const overrides = this.getOverrides(leaf);
    const existing = overrides.get(path);
    if (!existing)
      return;
    const next = existing.depth - 1;
    if (next <= 0)
      overrides.delete(path);
    else
      overrides.set(path, { ...existing, depth: next });
  }
  // ─── OFFSETS ──────────────────────────────────────────────────────────────
  saveOffset(leaf, nodePath, anchorPath, nodePos, anchorPos) {
    this.getOffsets(leaf).set(nodePath, {
      anchorPath,
      dx: nodePos.x - anchorPos.x,
      dy: nodePos.y - anchorPos.y
    });
  }
  resolvePos(leaf, nodePath, nativeByPath) {
    const rel = this.getOffsets(leaf).get(nodePath);
    if (!rel)
      return null;
    const anchor = nativeByPath.get(rel.anchorPath);
    if (!anchor)
      return null;
    return { x: anchor.pos.x + rel.dx, y: anchor.pos.y + rel.dy };
  }
  resolveAnyPos(leaf, nodePath, nativeByPath, overlayByPath) {
    var _a, _b;
    const native = (_a = nativeByPath.get(nodePath)) == null ? void 0 : _a.pos;
    if (native)
      return native;
    const overlay = overlayByPath.get(nodePath);
    if (overlay)
      return overlay;
    const rel = this.getOffsets(leaf).get(nodePath);
    if (!rel)
      return null;
    const nativeAnchor = (_b = nativeByPath.get(rel.anchorPath)) == null ? void 0 : _b.pos;
    if (nativeAnchor) {
      return {
        x: nativeAnchor.x + rel.dx,
        y: nativeAnchor.y + rel.dy
      };
    }
    const overlayAnchor = overlayByPath.get(rel.anchorPath);
    if (overlayAnchor) {
      return {
        x: overlayAnchor.x + rel.dx,
        y: overlayAnchor.y + rel.dy
      };
    }
    return null;
  }
  nativeAnchorOf(leaf, nodePath) {
    var _a, _b;
    return (_b = (_a = this.getOffsets(leaf).get(nodePath)) == null ? void 0 : _a.anchorPath) != null ? _b : nodePath;
  }
  // ─── DRAW ─────────────────────────────────────────────────────────────────
  drawOverlay(leaf, renderer) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o;
    const overrides = this.getOverrides(leaf);
    if (!overrides.size) {
      this.clearOverlay(leaf);
      return;
    }
    const PIXI = window.PIXI;
    if (!(PIXI == null ? void 0 : PIXI.Container) || !(PIXI == null ? void 0 : PIXI.Graphics) || !(PIXI == null ? void 0 : PIXI.Text))
      return;
    const host = this.findPixiHost(renderer);
    if (!host)
      return;
    let overlay = this.overlayByLeaf.get(leaf);
    if (!overlay) {
      overlay = new PIXI.Container();
      overlay.sortableChildren = true;
      overlay.eventMode = "none";
      host.addChild(overlay);
      this.overlayByLeaf.set(leaf, overlay);
    } else if (overlay.parent !== host) {
      (_b = (_a = overlay.parent) == null ? void 0 : _a.removeChild) == null ? void 0 : _b.call(_a, overlay);
      host.addChild(overlay);
    }
    while (overlay.children.length) {
      const c = overlay.children[0];
      overlay.removeChild(c);
      (_c = c.destroy) == null ? void 0 : _c.call(c);
    }
    const nativeNodes = this.collectRenderedNodes(renderer);
    const nativeByPath = /* @__PURE__ */ new Map();
    for (const n of nativeNodes) {
      const p = this.extractNodeId(n);
      const pos = this.extractRenderedPosition(n);
      if (p && pos)
        nativeByPath.set(p, { raw: n, pos });
    }
    const overlayResolved = /* @__PURE__ */ new Map();
    const mergedNodes = /* @__PURE__ */ new Map();
    const mergedEdges = /* @__PURE__ */ new Map();
    const sortedBranches = Array.from(overrides.entries()).sort((a, b) => a[1].order - b[1].order);
    for (const [rootPath, branch] of sortedBranches) {
      const anchorPos = this.resolveAnyPos(leaf, rootPath, nativeByPath, overlayResolved);
      if (!anchorPos)
        continue;
      const neighborhood = this.collectNeighborhood(rootPath, branch.depth);
      const rootDir = (_d = branch.dir) != null ? _d : this.computeRootDirection(rootPath, anchorPos, nativeByPath, branch.order);
      if (!branch.dir) {
        this.getOverrides(leaf).set(rootPath, { ...branch, dir: rootDir });
      }
      const coords = this.layoutBranch(leaf, rootPath, anchorPos, neighborhood, nativeByPath, rootDir);
      for (const edge of neighborhood.links) {
        const a = coords.get(edge.source);
        const b = coords.get(edge.target);
        if (!a || !b)
          continue;
        if (nativeByPath.has(edge.source) && nativeByPath.has(edge.target))
          continue;
        const key = this.edgeKey(edge.source, edge.target);
        const ex = mergedEdges.get(key);
        if (ex) {
          if (!ex.colors.includes(branch.color))
            ex.colors.push(branch.color);
        } else
          mergedEdges.set(key, { source: edge.source, target: edge.target, colors: [branch.color] });
      }
      for (const nodePath of neighborhood.nodes) {
        if (nodePath === rootPath || nativeByPath.has(nodePath))
          continue;
        const p = coords.get(nodePath);
        if (!p)
          continue;
        const existingResolved = this.resolvePos(leaf, nodePath, nativeByPath);
        if (!existingResolved) {
          this.saveOffset(leaf, nodePath, rootPath, p, anchorPos);
        }
        const finalPos = (_e = this.resolvePos(leaf, nodePath, nativeByPath)) != null ? _e : p;
        overlayResolved.set(nodePath, finalPos);
        const ex = mergedNodes.get(nodePath);
        if (ex) {
          if (!ex.colors.includes(branch.color))
            ex.colors.push(branch.color);
          if (!ex.owners.includes(rootPath))
            ex.owners.push(rootPath);
          ex.depth = Math.min(ex.depth, branch.depth);
        } else {
          mergedNodes.set(nodePath, {
            path: nodePath,
            pos: finalPos,
            colors: [branch.color],
            owners: [rootPath],
            depth: branch.depth,
            radius: this.estimateRadius(nodePath)
          });
        }
      }
    }
    for (const edge of mergedEdges.values()) {
      const a = (_i = (_h = (_f = nativeByPath.get(edge.source)) == null ? void 0 : _f.pos) != null ? _h : (_g = mergedNodes.get(edge.source)) == null ? void 0 : _g.pos) != null ? _i : this.resolveAnyPos(leaf, edge.source, nativeByPath, overlayResolved);
      const b = (_m = (_l = (_j = nativeByPath.get(edge.target)) == null ? void 0 : _j.pos) != null ? _l : (_k = mergedNodes.get(edge.target)) == null ? void 0 : _k.pos) != null ? _m : this.resolveAnyPos(leaf, edge.target, nativeByPath, overlayResolved);
      if (!a || !b)
        continue;
      const line = new PIXI.Graphics();
      line.zIndex = 1;
      line.eventMode = "none";
      if (edge.colors.length === 1) {
        line.lineStyle(1.8, edge.colors[0], 0.7);
        line.moveTo(a.x, a.y);
        line.lineTo(b.x, b.y);
      } else {
        edge.colors.forEach((color, i) => {
          const dx = b.x - a.x;
          const dy = b.y - a.y;
          const len = Math.max(1, Math.hypot(dx, dy));
          const nx = -dy / len;
          const ny = dx / len;
          const shift = (i - (edge.colors.length - 1) / 2) * 2;
          line.lineStyle(1.5, color, 0.8);
          line.moveTo(a.x + nx * shift, a.y + ny * shift);
          line.lineTo(b.x + nx * shift, b.y + ny * shift);
        });
      }
      overlay.addChild(line);
    }
    for (const node of mergedNodes.values()) {
      node.radius = Math.max(node.radius, node.colors.length > 1 ? 8 : 7);
      if (node.colors.length === 1) {
        const dot = new PIXI.Graphics();
        dot.zIndex = 2;
        dot.eventMode = "none";
        dot.beginFill(node.colors[0], 0.95);
        dot.lineStyle(1, 16777215, 0.95);
        dot.drawCircle(node.pos.x, node.pos.y, node.radius);
        dot.endFill();
        overlay.addChild(dot);
      } else {
        const sliceAngle = Math.PI * 2 / node.colors.length;
        node.colors.forEach((color, i) => {
          const wedge = new PIXI.Graphics();
          wedge.zIndex = 2;
          wedge.eventMode = "none";
          wedge.beginFill(color, 0.95);
          wedge.moveTo(node.pos.x, node.pos.y);
          wedge.arc(node.pos.x, node.pos.y, node.radius, -Math.PI / 2 + i * sliceAngle, -Math.PI / 2 + (i + 1) * sliceAngle);
          wedge.lineTo(node.pos.x, node.pos.y);
          wedge.endFill();
          overlay.addChild(wedge);
        });
        const border = new PIXI.Graphics();
        border.zIndex = 3;
        border.eventMode = "none";
        border.lineStyle(1, 16777215, 0.98);
        border.drawCircle(node.pos.x, node.pos.y, node.radius);
        overlay.addChild(border);
      }
      const lbl = new PIXI.Text(this.basename(node.path).replace(/\.md$/i, ""), { fontSize: 11, fill: node.colors[0] });
      lbl.zIndex = 4;
      lbl.resolution = 2;
      lbl.eventMode = "none";
      lbl.x = node.pos.x + node.radius + 4;
      lbl.y = node.pos.y - 7;
      overlay.addChild(lbl);
    }
    for (const [rootPath, branch] of sortedBranches) {
      const nativeRoot = (_n = nativeByPath.get(rootPath)) == null ? void 0 : _n.pos;
      const overlayRoot = (_o = mergedNodes.get(rootPath)) == null ? void 0 : _o.pos;
      const ringPos = nativeRoot != null ? nativeRoot : overlayRoot;
      if (!ringPos)
        continue;
      const ring = new PIXI.Graphics();
      ring.zIndex = 5;
      ring.eventMode = "none";
      ring.lineStyle(2.2, branch.color, 0.95);
      ring.drawCircle(ringPos.x, ringPos.y, 11);
      overlay.addChild(ring);
    }
  }
  // ─── LAYOUT ───────────────────────────────────────────────────────────────
  layoutBranch(leaf, rootPath, anchorPos, neighborhood, nativeByPath, rootDir) {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    const coords = /* @__PURE__ */ new Map();
    coords.set(rootPath, anchorPos);
    const adj = /* @__PURE__ */ new Map();
    for (const n of neighborhood.nodes)
      adj.set(n, []);
    for (const { source, target } of neighborhood.links) {
      (_a = adj.get(source)) == null ? void 0 : _a.push(target);
      (_b = adj.get(target)) == null ? void 0 : _b.push(source);
    }
    const parent = /* @__PURE__ */ new Map();
    const depth = /* @__PURE__ */ new Map();
    const bfsQueue = [rootPath];
    parent.set(rootPath, null);
    depth.set(rootPath, 0);
    while (bfsQueue.length) {
      const cur = bfsQueue.shift();
      for (const next of (_c = adj.get(cur)) != null ? _c : []) {
        if (parent.has(next))
          continue;
        parent.set(next, cur);
        depth.set(next, ((_d = depth.get(cur)) != null ? _d : 0) + 1);
        bfsQueue.push(next);
      }
    }
    const children = /* @__PURE__ */ new Map();
    for (const n of neighborhood.nodes)
      children.set(n, []);
    for (const n of neighborhood.nodes) {
      const p = parent.get(n);
      if (p)
        (_e = children.get(p)) == null ? void 0 : _e.push(n);
    }
    for (const arr of children.values()) {
      arr.sort((a, b) => this.basename(a).localeCompare(this.basename(b)));
    }
    for (const [p, native] of nativeByPath) {
      if (neighborhood.nodes.includes(p))
        coords.set(p, native.pos);
    }
    for (const n of neighborhood.nodes) {
      if (n === rootPath)
        continue;
      if (coords.has(n))
        continue;
      const saved = this.resolvePos(leaf, n, nativeByPath);
      if (saved)
        coords.set(n, saved);
    }
    const layoutNodes = /* @__PURE__ */ new Map();
    for (const n of neighborhood.nodes) {
      if (n === rootPath || nativeByPath.has(n))
        continue;
      const saved = this.resolvePos(leaf, n, nativeByPath);
      layoutNodes.set(n, {
        path: n,
        x: (_f = saved == null ? void 0 : saved.x) != null ? _f : 0,
        y: (_g = saved == null ? void 0 : saved.y) != null ? _g : 0,
        depth: (_h = depth.get(n)) != null ? _h : 1,
        radius: this.estimateRadius(n),
        labelWidth: this.estimateLabelWidth(n),
        fixed: !!saved
      });
    }
    const place = (node) => {
      var _a2, _b2;
      const nodePos = coords.get(node);
      if (!nodePos)
        return;
      const kids = ((_a2 = children.get(node)) != null ? _a2 : []).filter((k) => !nativeByPath.has(k));
      if (!kids.length)
        return;
      const d = (_b2 = depth.get(node)) != null ? _b2 : 0;
      const baseR = d === 0 ? this.ROOT_RADIUS : this.CHILD_RADIUS;
      const maxR = baseR * this.MAX_RADIUS_MULT;
      const dir = node === rootPath ? rootDir : this.computeChildDirection(leaf, node, nodePos, nativeByPath, coords, parent, rootDir);
      const dirAngle = Math.atan2(dir.y, dir.x);
      const sectorAngle = d === 0 ? Math.PI * 0.9 : Math.PI * 0.58;
      const newKids = kids.map((k) => layoutNodes.get(k)).filter((ln) => !!ln && !ln.fixed);
      const fixedKids = kids.map((k) => layoutNodes.get(k)).filter((ln) => !!ln && ln.fixed);
      for (const ln of fixedKids) {
        coords.set(ln.path, { x: ln.x, y: ln.y });
      }
      if (newKids.length) {
        const placements = this.planPlacements(dirAngle, sectorAngle, baseR, maxR, newKids);
        for (const pl of placements) {
          pl.node.x = nodePos.x + Math.cos(pl.angle) * pl.radius;
          pl.node.y = nodePos.y + Math.sin(pl.angle) * pl.radius;
        }
        this.relax(nodePos, dirAngle, sectorAngle, placements, maxR);
        for (const pl of placements) {
          coords.set(pl.node.path, { x: pl.node.x, y: pl.node.y });
        }
      }
      for (const k of kids) {
        place(k);
      }
    };
    place(rootPath);
    for (const [p, ln] of layoutNodes) {
      if (!coords.has(p)) {
        coords.set(p, { x: ln.x, y: ln.y });
      }
    }
    return coords;
  }
  planPlacements(dirAngle, sectorAngle, baseR, maxR, nodes) {
    if (!nodes.length)
      return [];
    const half = sectorAngle / 2;
    const offsets = this.centeredOffsets(nodes.length);
    const maxOff = Math.max(...offsets.map(Math.abs), 0);
    const maxDiam = Math.max(...nodes.map((n) => n.radius * 2 + Math.min(30, n.labelWidth * 0.2)));
    const minChord = maxDiam + this.NODE_PADDING * 2;
    const baseStep = maxOff === 0 ? 0.01 : (half - 0.05) / maxOff;
    const angleStep = Math.max(0.12, baseStep);
    let r = Math.max(baseR, angleStep > 0 ? minChord / (2 * Math.sin(angleStep / 2)) : baseR);
    r = Math.max(r, 80 + Math.max(...nodes.map((n) => n.radius + n.labelWidth * 0.15)));
    if (r <= maxR) {
      return nodes.map((n, i) => ({
        node: n,
        angle: dirAngle + offsets[i] * angleStep,
        radius: r
      }));
    }
    const rowCount = Math.max(2, Math.ceil(r / maxR));
    const rows = this.buildRows(nodes.length, rowCount);
    const result = [];
    for (let ri = 0; ri < rows.length; ri++) {
      const row = rows[ri];
      const rowNodes = row.map((i) => nodes[i]);
      const rowOff = this.centeredOffsets(row.length);
      const rowMaxOff = Math.max(...rowOff.map(Math.abs), 0);
      const rowStep = rowMaxOff === 0 ? 0.01 : Math.max(0.12, (half - 0.05) / rowMaxOff);
      const rowDiam = Math.max(...rowNodes.map((n) => n.radius * 2 + Math.min(30, n.labelWidth * 0.2)));
      let rowR = Math.max(baseR + ri * this.ROW_GAP, rowDiam / (2 * Math.sin(rowStep / 2)));
      rowR = Math.min(rowR, maxR);
      for (let i = 0; i < row.length; i++) {
        result.push({
          node: nodes[row[i]],
          angle: dirAngle + rowOff[i] * rowStep,
          radius: rowR
        });
      }
    }
    return result;
  }
  relax(anchor, dirAngle, sectorAngle, placements, maxR) {
    if (placements.length < 2)
      return;
    const minA = dirAngle - sectorAngle / 2 + 0.04;
    const maxA = dirAngle + sectorAngle / 2 - 0.04;
    for (let iter = 0; iter < this.RELAX_ITERS; iter++) {
      for (let i = 0; i < placements.length; i++) {
        for (let j = i + 1; j < placements.length; j++) {
          const a = placements[i].node;
          const b = placements[j].node;
          if (a.fixed || b.fixed)
            continue;
          const dx = b.x - a.x;
          const dy = b.y - a.y;
          const dist = Math.hypot(dx, dy);
          const minD = a.radius + b.radius + this.NODE_PADDING + Math.min(20, (a.labelWidth + b.labelWidth) * 0.07);
          if (dist >= minD || dist < 1e-3)
            continue;
          const push = (minD - dist) * 0.55;
          const nx = dx / dist;
          const ny = dy / dist;
          const aMid = Math.atan2(a.y - anchor.y, a.x - anchor.x);
          const bMid = Math.atan2(b.y - anchor.y, b.x - anchor.x);
          a.x -= nx * push * 0.5;
          a.y -= ny * push * 0.5;
          b.x += nx * push * 0.5;
          b.y += ny * push * 0.5;
        }
      }
      for (const pl of placements) {
        const n = pl.node;
        if (n.fixed)
          continue;
        const dx = n.x - anchor.x;
        const dy = n.y - anchor.y;
        let angle = Math.atan2(dy, dx);
        let radius = Math.hypot(dx, dy);
        angle = Math.max(minA, Math.min(maxA, angle));
        const minR = pl.radius + Math.min(20, n.labelWidth * 0.1);
        radius = Math.max(minR, radius);
        radius = Math.min(maxR, radius);
        n.x = anchor.x + Math.cos(angle) * radius;
        n.y = anchor.y + Math.sin(angle) * radius;
      }
    }
  }
  // ─── DIRECTION ────────────────────────────────────────────────────────────
  /** For root: away from centroid of native neighbors */
  computeRootDirection(rootPath, anchorPos, nativeByPath, branchOrder) {
    const neighbors = this.getNeighbors(rootPath).filter((p) => p !== rootPath && nativeByPath.has(p)).map((p) => nativeByPath.get(p).pos);
    if (neighbors.length) {
      const cx = neighbors.reduce((s, p) => s + p.x, 0) / neighbors.length;
      const cy = neighbors.reduce((s, p) => s + p.y, 0) / neighbors.length;
      return this.normalize({ x: anchorPos.x - cx, y: anchorPos.y - cy });
    }
    const angle = -Math.PI / 2 + branchOrder * 0.65;
    return { x: Math.cos(angle), y: Math.sin(angle) };
  }
  /** For child overlay node: away from the native anchor that "owns" it */
  computeChildDirection(leaf, nodePath, nodePos, nativeByPath, coords, parentMap, fallback) {
    var _a;
    const anchorPath = this.nativeAnchorOf(leaf, nodePath);
    const anchorPos = (_a = nativeByPath.get(anchorPath)) == null ? void 0 : _a.pos;
    if (anchorPos) {
      const v = { x: nodePos.x - anchorPos.x, y: nodePos.y - anchorPos.y };
      const len = Math.hypot(v.x, v.y);
      if (len > 0.5)
        return { x: v.x / len, y: v.y / len };
    }
    const parentPath = parentMap.get(nodePath);
    if (parentPath) {
      const parentPos = coords.get(parentPath);
      if (parentPos) {
        const v = { x: nodePos.x - parentPos.x, y: nodePos.y - parentPos.y };
        const len = Math.hypot(v.x, v.y);
        if (len > 0.5)
          return { x: v.x / len, y: v.y / len };
      }
    }
    return this.normalize(fallback);
  }
  // ─── HELPERS ──────────────────────────────────────────────────────────────
  centeredOffsets(count) {
    if (count <= 0)
      return [];
    if (count === 1)
      return [0];
    const out = [0];
    let s = 1;
    while (out.length < count) {
      out.push(-s);
      if (out.length < count)
        out.push(s);
      s++;
    }
    return out;
  }
  buildRows(count, rowCount) {
    const rows = Array.from({ length: rowCount }, () => []);
    for (let i = 0; i < count; i++)
      rows[i % rowCount].push(i);
    return rows.filter((r) => r.length > 0);
  }
  collectNeighborhood(startPath, maxDepth) {
    const nodes = /* @__PURE__ */ new Set();
    const links = /* @__PURE__ */ new Set();
    const visited = /* @__PURE__ */ new Set();
    const queue = [{ path: startPath, d: 0 }];
    while (queue.length) {
      const { path, d } = queue.shift();
      if (visited.has(path))
        continue;
      visited.add(path);
      nodes.add(path);
      if (d >= maxDepth)
        continue;
      for (const nb of this.getNeighbors(path)) {
        nodes.add(nb);
        links.add(this.edgeKey(path, nb));
        if (!visited.has(nb))
          queue.push({ path: nb, d: d + 1 });
      }
    }
    return {
      nodes: Array.from(nodes),
      links: Array.from(links).map((e) => {
        const [s, t] = e.split("\u2192");
        return { source: s, target: t };
      })
    };
  }
  getNeighbors(path) {
    var _a;
    const out = /* @__PURE__ */ new Set();
    const resolved = (_a = this.app.metadataCache.resolvedLinks) != null ? _a : {};
    if (resolved[path])
      for (const d of Object.keys(resolved[path]))
        out.add(d);
    for (const [src, dests] of Object.entries(resolved)) {
      if (dests && path in dests)
        out.add(src);
    }
    return Array.from(out);
  }
  estimateRadius(path) {
    const l = this.basename(path).replace(/\.md$/i, "").length;
    return 8 + Math.min(7, Math.ceil(l / 6) * 0.6);
  }
  estimateLabelWidth(path) {
    return Math.max(24, this.basename(path).replace(/\.md$/i, "").length * 6.5);
  }
  normalize(v) {
    const len = Math.hypot(v.x, v.y) || 1;
    return { x: v.x / len, y: v.y / len };
  }
  distance(a, b) {
    return Math.hypot(a.x - b.x, a.y - b.y);
  }
  edgeKey(a, b) {
    return [a, b].sort().join("\u2192");
  }
  safeRefresh(view) {
    var _a, _b;
    try {
      if (typeof ((_a = view == null ? void 0 : view.renderer) == null ? void 0 : _a.queueRender) === "function") {
        view.renderer.queueRender();
        return;
      }
    } catch (e) {
    }
    try {
      if (typeof (view == null ? void 0 : view.update) === "function") {
        view.update();
        return;
      }
    } catch (e) {
    }
    try {
      if (typeof ((_b = view == null ? void 0 : view.engine) == null ? void 0 : _b.updateSearch) === "function") {
        view.engine.updateSearch();
      }
    } catch (e) {
    }
  }
  clearOverlay(leaf) {
    var _a, _b, _c, _d;
    const overlay = this.overlayByLeaf.get(leaf);
    if (overlay) {
      try {
        while (overlay.children.length) {
          const c = overlay.children[0];
          overlay.removeChild(c);
          (_a = c.destroy) == null ? void 0 : _a.call(c);
        }
        (_c = (_b = overlay.parent) == null ? void 0 : _b.removeChild) == null ? void 0 : _c.call(_b, overlay);
        (_d = overlay.destroy) == null ? void 0 : _d.call(overlay, { children: true });
      } catch (e) {
      }
    }
    this.overlayByLeaf.delete(leaf);
    this.offsetsByLeaf.delete(leaf);
  }
  findPixiHost(renderer) {
    var _a;
    for (const key of ["stage", "container", "viewport", "app"]) {
      const v = key === "app" ? (_a = renderer == null ? void 0 : renderer.app) == null ? void 0 : _a.stage : renderer == null ? void 0 : renderer[key];
      if (this.isPixiContainer(v))
        return v;
    }
    for (const key of Object.keys(renderer != null ? renderer : {})) {
      try {
        const v = renderer[key];
        if (this.isPixiContainer(v))
          return v;
      } catch (e) {
      }
    }
    return null;
  }
  isPixiContainer(v) {
    return !!v && typeof v.addChild === "function" && Array.isArray(v.children);
  }
  collectRenderedNodes(renderer) {
    const found = [];
    const seen = /* @__PURE__ */ new WeakSet();
    const walk = (v, d) => {
      if (d > 4 || !v || typeof v !== "object" || seen.has(v))
        return;
      seen.add(v);
      if (Array.isArray(v)) {
        for (const i of v)
          walk(i, d + 1);
        return;
      }
      if (this.extractNodeId(v) && this.extractRenderedPosition(v))
        found.push(v);
      for (const k of Object.keys(v)) {
        try {
          walk(v[k], d + 1);
        } catch (e) {
        }
      }
    };
    walk(renderer, 0);
    const dedup = /* @__PURE__ */ new Map();
    for (const item of found) {
      const id = this.extractNodeId(item);
      if (id && !dedup.has(id))
        dedup.set(id, item);
    }
    return Array.from(dedup.values());
  }
  extractRenderedPosition(obj) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l;
    const variants = [
      [obj == null ? void 0 : obj.x, obj == null ? void 0 : obj.y],
      [(_a = obj == null ? void 0 : obj.position) == null ? void 0 : _a.x, (_b = obj == null ? void 0 : obj.position) == null ? void 0 : _b.y],
      [(_c = obj == null ? void 0 : obj.node) == null ? void 0 : _c.x, (_d = obj == null ? void 0 : obj.node) == null ? void 0 : _d.y],
      [(_f = (_e = obj == null ? void 0 : obj.node) == null ? void 0 : _e.position) == null ? void 0 : _f.x, (_h = (_g = obj == null ? void 0 : obj.node) == null ? void 0 : _g.position) == null ? void 0 : _h.y],
      [(_i = obj == null ? void 0 : obj.graphics) == null ? void 0 : _i.x, (_j = obj == null ? void 0 : obj.graphics) == null ? void 0 : _j.y],
      [(_k = obj == null ? void 0 : obj.circle) == null ? void 0 : _k.x, (_l = obj == null ? void 0 : obj.circle) == null ? void 0 : _l.y]
    ];
    for (const [x, y] of variants) {
      if (typeof x === "number" && typeof y === "number" && Number.isFinite(x) && Number.isFinite(y))
        return { x, y };
    }
    return null;
  }
  extractNodeId(v) {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    if (!v)
      return null;
    if (typeof v === "string")
      return v;
    return (_h = (_g = (_e = (_c = (_a = v.id) != null ? _a : v.path) != null ? _c : (_b = v.file) == null ? void 0 : _b.path) != null ? _e : (_d = v.node) == null ? void 0 : _d.id) != null ? _g : (_f = v.node) == null ? void 0 : _f.path) != null ? _h : null;
  }
  extractPathFromArgs(args) {
    var _a;
    for (const arg of args) {
      if (typeof arg === "string" && arg.endsWith(".md"))
        return arg;
      if (arg && typeof arg === "object") {
        const id = this.extractNodeId(arg);
        if ((_a = id == null ? void 0 : id.endsWith) == null ? void 0 : _a.call(id, ".md"))
          return id;
      }
    }
    return null;
  }
  findMouseEvent(args) {
    for (const arg of args) {
      if (typeof PointerEvent !== "undefined" && arg instanceof PointerEvent)
        return arg;
      if (typeof MouseEvent !== "undefined" && arg instanceof MouseEvent)
        return arg;
    }
    return null;
  }
  basename(path) {
    const parts = path.split(/[\\/]/);
    return parts[parts.length - 1] || path;
  }
};


/* nosourcemap */